### ISSUE TITLE
Is there a way to get the path relative and full from the selected directory for showDirectoryPicker

### ISSUE THREAD

**Issue by delebash** [jimmywarting/native-file-system-adapter#19]
Any way to get the path of the selected directory?

I know you can get the name of the directory from the directoryHandle but I have not seen any methods or props to get the full path

I also am aware of .resolve() method but I don't understand if this can be used to get the path of the selected directory.
I also looked at File and Directory Entries API but still did not find a way to get selected path.

My whole goal is for the user to click a button > select a directory > have that path displayed in a text box.  If the File System Access Api can't do this do you know another method?  I do not want to upload any files, just get the path of selected directory.

Thanks,
Dan

**Comment by jimmywarting** [comment]
Hi Dan 👋 

There is no possible way to do this.
it's hidden for security issues.

The best you can do is getting access to a folder handle (of some root dir)
And then select any sub directory form the Folder Handle in a own UI
then you can figure out the relative path manually by walking

Absolute path is unfortunately not an option...

**Comment by delebash** [comment]
Thanks, that is an interesting idea I will give it a try.  Cheers
