### ISSUE TITLE
web-streams-polyfill dependency upgrade

### ISSUE THREAD

**Issue by fryck** [jimmywarting/native-file-system-adapter#20]
Hello, I have an error with the dynamic import of `web-streams-polyfill` package (webpack)

```
external "https://cdn.jsdelivr.net/npm/web-streams-polyfill@2.1.1/dist/ponyfill.es2018.mjs"
The target environment doesn't support dynamic import() syntax so it's not possible to use external type 'module' within a script
```

Could you upgrade the dependency to 3.1.1 ?

Thanks !

**Comment by jimmywarting** [comment]
I'm using:
https://github.com/jimmywarting/native-file-system-adapter/blob/8a5393c0b15a57e3c7138cfa136f6195a0582685/src/FileSystemWritableFileStream.js#L3-L4

**Comment by fryck** [comment]
Yes, but in your catch you have `() => import('web-streams-polyfill').then(r => r.WritableStream)` and on your package.json 

```
"dependencies": {
    "web-streams-polyfill": "^2.1.1"
  },
```

but the lastest version of this package is 3.1.1

**Comment by jimmywarting** [comment]
oh, right

**Comment by fryck** [comment]
In the downloader adapter it seems that you use the older version too

https://github.com/jimmywarting/native-file-system-adapter/blob/8a5393c0b15a57e3c7138cfa136f6195a0582685/src/adapters/downloader.js#L27

:)

**Comment by jimmywarting** [comment]
Thanks for pointing that out

**Comment by fryck** [comment]
Unfornutately, I have the same error with the latest web-streams-polyfill version

```
external "https://cdn.jsdelivr.net/npm/web-streams-polyfill@3/dist/ponyfill.es2018.mjs"
The target environment doesn't support dynamic import() syntax so it's not possible to use external type 'module' within a script
```

I don't know how to fix this issue, I use your package in a nextjs application (with webpack 5)

**Comment by jimmywarting** [comment]
could it be that webpack don't like seeing that dynamic http import and rewrites it?

Maybe something like this can help? https://github.com/node-fetch/node-fetch/issues/1279#issuecomment-915063354

**Comment by fryck** [comment]
Thanks, according to my error, maybe it's due to wrong target version in this project ?

https://github.com/MattiasBuelens/web-streams-polyfill/blob/master/tsconfig.json

**Comment by jimmywarting** [comment]
Maybe, anyway i publish 1.1.0 with newer version of web streams

**Comment by fryck** [comment]
@jimmywarting Author of `web-streams-polyfill` answered me about this issue: https://github.com/MattiasBuelens/web-streams-polyfill/issues/94#issuecomment-925840376

Like I said, I've tried to build my app with target: 'esnext' and module: 'esnext' but I got the same error.

I don't know how to fix that, really :/

**Comment by razvantim** [comment]
I have the same problem as @fryck . I'm trying to integrate this component into an Angular 12 solution.

**Comment by salimkanoun** [comment]
hi all, thanks for your amazing work, same issue for me, unable to integrate native-file-system-adapter with react 18/webpack 5 because of the dynamic import (so reverted to streamsaver).

**Comment by denis111** [comment]
The same problem here with Angular 14. Firstly it was complaining about topLevelAwait and something like node:path which seems to be solved with custom webpack config:
```javascript
var webpack = require('webpack');

module.exports = {
  experiments: {
    topLevelAwait: true,
    outputModule: true
  },
  plugins: [
    new webpack.NormalModuleReplacementPlugin(/node:/, (resource) => {
      resource.request = resource.request.replace(/^node:/, "");
    }),
  ]
};
```
I had to configure custom-webpack buider only for this. But now I have the same problem with dynamic import:
The target environment doesn't support dynamic import() syntax so it's not possible to use external type 'module' within a script.

I think all the external polyfills should be optional anyway because what if you want offline web application or in some restricted environment without loading any external files or something...

**Comment by jbhurruth** [comment]
@jimmywarting I've just hit this problem too. Do you have any ideas on how to resolve it?
