### ISSUE TITLE
Add support for persisting file folder handle in indexdb for permissions

### ISSUE THREAD

**Issue by delebash** [jimmywarting/native-file-system-adapter#23]
In this article  https://web.dev/browser-fs-access/ a method was shown to store file and folder handles in indexdb.  This would persist permission  after closing browser so user is not asked for permission again.

**Comment by jimmywarting** [comment]
Yes, if you use the native adapter then you can store the handle in IndexedDB. for the other adapters you don't really need to store the handle cuz you already have sandbox access
