### ISSUE TITLE
showSaveFilePicker() doesn't cancel download after page reload

### ISSUE THREAD

**Issue by vrindarx** [jimmywarting/native-file-system-adapter#30]
The download seems in progress even if the page's refresh and no javascript is using it.

**Comment by jimmywarting** [comment]
Do you know if you are using native `showSaveFilePicker` or not?

**Comment by vrindarx** [comment]
Yes I'm using `showSaveFilePicker`

**Comment by jimmywarting** [comment]
> Yes I'm using showSaveFilePicker

There are two/three method when using the `showSaveFilePicker`

- Either it will use the native `globalThis. showSaveFilePicker` method. 
- Or it will result in generating a blob and later save the file using good old Blob + `a[href=blob_url][download=name]` (doubt that you are using this one as it would most likely not make the download hang)
- The third optional option is to potentially register use the service worker for piping data directly to the disk.

**Comment by vrindarx** [comment]
The problem seems to be fixed, I've been using the service worker method to save the data. Thanks 👍🏻
