### ISSUE TITLE
Downloading file doesn't work in Safari 16.1

### ISSUE THREAD

**Issue by adamblok** [jimmywarting/native-file-system-adapter#43]
Hi,

The code:

```javascript
  const fileHandle = await showSaveFilePicker({
    _preferPolyfill: false,
    suggestedName: 'test.jpg'
  });

  if (fileHandle) {
    const response = await fetch('https://test.com/test.jpg');
    const writable = await fileHandle.createWritable();
    await response.body.pipeTo(writable);
  }
```

Works well in Chrome, Opera and FF.

But on Safari 16.1 on Mac it throws the error:
**TypeError: Constructor requires 'new' operator**

It comes from this line:
```javascript
const writable = await fileHandle.createWritable();
```

Am I doing something wrong here?

**Comment by jimmywarting** [comment]
Do you have some more detailed stack trace of what lines / files are being called?
or a jsfiddle demo?

---

fyi. in the case of downloading something from a url with fetch, then i would rather suggest doing something like
```js
const a = document.createElement('a')
a.download = 'test.png'
a.href = 'https://test.com/test.jpg'
a.click()
```
as download would be able to work in the background and would require the main thread to be active.

**Comment by adamblok** [comment]
Just wanted to confirm that the issue was related to the way how Babel transpiles code. More information: 
[https://stackoverflow.com/questions/62531025/typeerror-htmlelement-constructor-new-is-required](https://stackoverflow.com/questions/62531025/typeerror-htmlelement-constructor-new-is-required)

Changing Babel configuration resolved the issue :).
