### ISSUE TITLE
Angular Service Worker breaks on iframe fallback

### ISSUE THREAD

**Issue by mate-szucs** [jimmywarting/native-file-system-adapter#51]
In case of hidden iframe fallback, the Angular Service Worker catches the download URL and tries to route it within the SinglePageApplication.
Since the download filename is not matching to any route, this attempt results the following error: 
ERROR Error: Uncaught (in promise): Error: NG04002 noMatchError

The problem discussed here in general:
https://stackoverflow.com/questions/60431490/angular-router-is-catching-url-from-iframe

Fortunately Angular has a URL parameter, to prevent the SW to process the request.
?ngsw-bypass=true

An option that can trigger "ngsw-bypass" parameter would be very useful.

**Comment by jimmywarting** [comment]
Hmm, don't really wish to do any angular (or anything else) specific option for any library, just b/c it works a little bit different...

however... if the error comes from a service worker then perhaps maybe a [stopImmediatePropagation](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation) (and / or `stopPropagation`) in this function may help. 
https://github.com/jimmywarting/native-file-system-adapter/blob/f4f97e87e7c8a377bd4924dca0550711b1be07dc/example/sw.js#L76-L84

> If several listeners are attached to the same element for the same event type, they are called in the order in which they were added. If stopImmediatePropagation() is invoked during one such call, no remaining listeners will be called.

it would stop angular from doing it's thing... then we don't need any option and i would be okey with this solution

---

However it would maybe not be such a bad thing if you where able to specify exactly what url you would trigger the download from. the url would be added to the download history and if you want to re-download that file then it would be good if you could get to that page/url that would be able to initiate that download again. 

But i don't know if i want to support such feature
