### ISSUE TITLE
Question about using native-file-system-adapter with streamsaver

### ISSUE THREAD

**Issue by JulieMarie** [jimmywarting/native-file-system-adapter#53]
Hey Jimmy,

What I'm wanting to do is to query for a file name (using `showSaveFilePicker`, then go do some work in the background, and at a later date, save a stream using `createWriteStream`.  I know I saw where you mention that this library can be used for streaming, but you need a service worker.  I'm just trying to figure out if I can get the filename early on and then save the stream later.  It could be a difference of minutes before I'm ready to save the stream and I don't want to have to query for the filename at that time.

Is this possible?

**Comment by jimmywarting** [comment]
> I know that this library can be used for streaming, but you need a service worker

Service worker are optional.

Calling `showSaveFilePicker()` may end up calling the native `window.showSaveFilePicker()`.
But only if it's Blink (chrome, edge, opera, brave) which have this feature builtin.
In which case it dose not need a service worker at all.
Then you will get a native `FileSystemFileHandle` back
(and the user can change the file name in the save dialog)

if it is not Blink (like firefox or safari) then there is no native `window.showSaveFilePicker()` then it will resort to either using a service worker and save the file much like [streamsaver.js](https://github.com/jimmywarting/StreamSaver.js) dose (by kind of emulating how a server saves a file)
And you will get back a fake (polyfilled) `FileSystemFileHandle` - this can't be saved in IndexedDB

if you don't have a service worker installed on your site, then it will fallback to creating a in memory `FileSystemFileHandle` and construct a [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob). then when you close the writeable stream you get back from calling `handle.createWriteStream()` then it will trigger a classical download using something like:
```js
a = document.createElement('a')
a.href = URL.createObjectURL(blob)
a.download = filename
a.click()
```
and the save dialog will show up after you have closed the writable stream.

The service worker solution is obviously a better choice for saving larger file that can't be stored in memory (like 500mb+)
cuz it's better stream friendly

So when you are actually calling `showSaveFilePicker` then there is 3 ways it can go
1. uses native `window.showSaveFilePicker()` if available
2. emulates how a server saves file by triggering a download link generated by service worker (which you can get a writable stream from)
3. if none of the 2 solution above is working it fallbacks to constructing blob & uses `URL.createObjectURL`

if you are using native `showSaveFilePicker` (only available in Blink) then you can save this file handle in `IndexedDB` and forget about it. then when you are ready you could get the file handle from indexeddb and call `fileHandle.createWriteStream()`.
doing this will created a empty file on the users computer. that you can later write to

the alternative is to ask for write permission to a directory by using `showDirectoryPicker()` then you could create a file when you need to (or when you are ready) but you won't get any user provided filename or save dialogs. you have to programmatically set a file name yourself and it will happen completely in the background unless you show them some kind of download UI.
again this is only available in blink...

---

it could be tuff to call `showSaveFilePicker` at a later stage as native `showSaveFilePicker` may only be called on user interaction such as a onclick.
but the service worker and or the blob solution may not. it might work or it might be blocked.

**Comment by JulieMarie** [comment]
Thank you so much for your prompt response Jimmy!  

I want to call `showSaveFilePicker` early on, that's perfect.  So once I have the native `FileSystemFileHandle` (if I'm using a Blink browser), how do I create the writable stream?  I *think* (can't remember all I tried yesterday) I tried like `const fileStream = fileHandle.createWriteStream()` (and then I create a `readableStream` and `readableStream.pipeTo(fileStream)`), but it just hung on the `createWriteStream` statement.  It's probably something easy I missed!

**Comment by jimmywarting** [comment]
then perhaps something like this:

```js
let p
let query = (method, ...args) => (p ??= new Promise(rs => {
  const open = indexedDB.open('clientmyadmin-kv')
  open.onupgradeneeded = () => open.result.createObjectStore('kv')
  open.onsuccess = () => {
    const db = open.result
    query = (method, ...args) => {
      const q = db.transaction('kv', 'readwrite').objectStore('kv')[method](...args)
      return new Promise((rs, rj) => {
        q.onsuccess = () => rs(q.result)
        q.onerror = () => rj(q.error)
      })
    }
    rs()
  }
})).then(() => query(method, ...args))

/**
 * simple key/value storage for indexedDB that can do most things
 * with just one function and some arguments and async/await
 * 
 * @typedef {keyof IDBObjectStore} IDBObjectStoreMethods
 * @type {<M extends IDBObjectStoreMethods>(method: M, ...args: Parameters<IDBObjectStore[M]>) => Promise<ReturnType<IDBObjectStore[M]['result']>>}
 */
const kv = (...args) => query(...args)

const options = {
  types: [
    {
      description: 'Text Files',
      accept: {
        'text/plain': ['.txt', '.md'],
        'text/html': ['.html', '.htm']
      }
    },
    {
      description: 'Images',
      accept: {
        'image/*': ['.png', '.gif', '.jpeg', '.jpg']
      }
    }
  ],
  suggestedName: 'README.md'
}
const handle = await window.showSaveFilePicker({ options })
await kv('put', handle, 'filehandle') // store the file handle for later use.

// Sleep 10s
await new Promise(rs => setTimeout(rs, 10000)) // sleep

// get the old file handle (with the key 'filehandle')
const fileHandle = await kv('get', 'filehandle')
const writable = await fileHandle.createWritable()
const readable = new Response('hello world').body
readable.pipeTo(writable)
```
