### ISSUE TITLE
showSaveFilePicker resolves without prompting

### ISSUE THREAD

**Issue by acurrieclark** [jimmywarting/native-file-system-adapter#59]
I could have sworn I had this working correctly previously, but whenever I run the example code to `showSaveFilePicker`, the handle resolves immediately without prompting.

I have the function being called from a click handler on a button in a SveltKit app.

```ts
import { showSaveFilePicker } from "native-file-system-adapter";

const fileHandle = await showSaveFilePicker({
  _preferPolyfill: false,
  suggestedName: "Untitled.png",
  types: [
    { accept: { "image/png": ["png"] } },
    { accept: { "image/jpg": ["jpg"] } },
    { accept: { "image/webp": ["webp"] } },
  ],
  excludeAcceptAllOption: false, // default
});

console.log(fileHandle); // <- this is shown immediately
```

**Comment by jimmywarting** [comment]
What browser are you using?

**Comment by acurrieclark** [comment]
Sorry, that would have been useful! Brave browser Version 1.50.121 Chromium: 112.0.5615.138 (Official Build) (x86_64)

**Comment by jimmywarting** [comment]
Hmm, ok...
that's good to know. seems like brave dose not have [file system access](https://github.com/WICG/file-system-access/) enabled.
Tried looking for it on `window` but wasn't there... even doe it's more a Blink implementation. 
found a flag in `brave://flags/#file-system-access-api` that showed me that it was just disabled.

firefox just don't have it... out of concern for unwanted access...

So the reason why you might get it a file handle immediately is b/c there is nothing that can prompt you and ask you where you want to save the file in the first place if there is no real `showSaveFilePicker` implementation.

**Comment by jimmywarting** [comment]
I sometimes gets some confusing question on github issues as i most often have to guess what method of choises they use in order to save the files.

there are currently 3 method in place, 1) native 2) service worker 3) building a blob
So it gets a bit hard to trying figuring out the path it would take. 

so i want to switch out `_preferPolyfill: false` to `preferedMethods`
```diff
const fileHandle = await showSaveFilePicker({
- _preferPolyfill: false
+ _preferedMethods: [
+   'native', // req native support for window.showSaveFilePicker
+   'service-worker',  // requires installing a service worker to allow streaming large files
+   'constructing-blob'  // easiest/oldest method that req. more RAM but is fine for smaller file
+ ],
  suggestedName: "Untitled.png",
  types: [
    { accept: { "image/png": ["png"] } },
    { accept: { "image/jpg": ["jpg"] } },
    { accept: { "image/webp": ["webp"] } },
  ],
  excludeAcceptAllOption: false, // default
});
```

**Comment by acurrieclark** [comment]
Interesting. I am sure that it was working in Brave before. There is actually [an open issue](https://github.com/brave/brave-browser/issues/29411) on their repo right now.

Thanks for the feedback. Will look out for the updated signature.
