### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by SargisPlusPlus** [jimmywarting/native-file-system-adapter#69]
I noticed that `createWritable` was added in the [last commit ](https://github.com/jimmywarting/native-file-system-adapter/pull/62)

When will this be published to NPM?

**Comment by driesd** [comment]
@jimmywarting Can we help with something to get the latest veersion released?

**Comment by jimmywarting** [comment]
Can try to get it published later today when i get back home in 2-3h or so. 
Send me a reminder if i forget

**Comment by SargisPlusPlus** [comment]
@jimmywarting reminder 🙏

**Comment by jimmywarting** [comment]
@SargisPlusPlus thanks. It's released now.
